### PR TITLE
[WIP] Automated deployment

### PR DESCRIPTION
**Pull request by YannickRe**
We're super excited about your automation work @gavinbarron! @LuiseFreese asked me to validate the work and provide feedback, and overall I'm delighted that this drastically reduced the deployment time!
We did notice some small issues and like to ask for some additional functionality, so we can reuse this script for upgrades as well.

**First run: cannot create the "templates" container in the storage account**
Whatever I do, the script always fails to create the "templates" container for me. This of course fails the rest of the deployment. I worked around it by manually creating it, and then rerunning but that's not a great workaround :
MicrosoftTeams-image (2)
)

**Script parameters + documentation**
The script takes already a **SubscriptionId** parameter, and we'd like the option to optionally provide a **ResourceGroup** parameter too.
Given both optional parameters, we'd think this could be made more clear:
- Explain both optional parameters in the documentation, and make it clear how they can be used
- Ask for confirmation in the script for the parameters like "does this look correct?", and only on approval we start the script

**Rerunning of the script**
We'd like the script to be idempotent, so you can run it even if a previous run has occurred. This is helpful when parts of the deployment failed, or when the ARM template gets updated in an upgrade scenario.
Currently, there are some situations where that isn't happening as clean as we'd like it to be.

With the app registration:
MicrosoftTeams-image (3)
Also, it creates a NEW client secret on every run and keeps the old one. We feel like the old one should be removed, but can't really assess the impact. Any idea?

With the uploading/updating of the template files
MicrosoftTeams-image (4)

With adding permissions to the managed identity
MicrosoftTeams-image (5)

**Downloading of the template files**
Looking into this whole approach, we started wondering if we really need the deployment storage account. Given that we already copy all the files with a GIT checkout to the CLI storage account, can't we just use it from there?
We're unsure if this is a good idea or not, so we appreciate your input and ideas regarding this.

Let us know what you think about all of this? We are already more than grateful for the work you already did, so if you don't feel like taking up these improvements (all or part of them), just tell us. We can share the work if you'd like.

### CODE REVIEW

**Comment by gavinbarron** [comment]
Thanks for the feedback @YannickRe :) 

Can't create the container. 
 - Can you please validate that the account you are using has the Contributor role assignment at the subscription level? I ran into this when I had an account with the classic owner permission but no modern permission assigned. I believe that permission level is called out as a pre-requisite at present.
 
 Optional ResourceGroup parameter
- ❤️ I had this in there, but took it out based on feedback. 

Script idempotency
- Cool, happy to make this better and all of that makes sense to me.
- The upload of templates is probably failing as the container and SasToken step failed, might need to set this script up with `$ErrorActionPreference = Stop`, thoughts?

Downloading template files
Options:
1. We could likely get the Blob URL for the templates cloned into cloud shell and use that
1. I believe we can use the raw github url for the main branch as the input to the ARM deployment which simplifies the script a whole lot. Will investigate and confirm.

Assuming that 2 is feasible it would be my preferred approach, but I'll differ to you and @LuiseFreese as your preference here and go that way
 
 And I'm more than happy to help get this wrapped up.

**Comment by YannickRe** [comment]
> Can't create the container.
> Can you please validate that the account you are using has the Contributor role assignment at the subscription level? I ran into this when I had an account with the classic owner permission but no modern permission assigned. I believe that permission level is called out as a pre-requisite at present.

Ok, that makes sense. I only have classic administrator rights, not a modern permission level assigned. I'll try again with that permission. It's ok if this is a prerequisite for now, but in that case I would propose two things:
- we document this prerequisite and the associated error message clearly
- we try and assign this permission on the Resource Group level to circumvent this

> Script idempotency
> - The upload of templates is probably failing as the container and SasToken step failed, might need to set this script up with $ErrorActionPreference = Stop, thoughts?

It only fails the second time (first time works after manually creating the container), it doesn't fail to get the SAS token (but that doesn't matter as it isn't used, because the script uses the `--login` option). I will see if this is fixed with the previous point when adding a modern Contributor permission level.

> Downloading template files
> Options:
> 1. We could likely get the Blob URL for the templates cloned into cloud shell and use that
> 2. I believe we can use the raw github url for the main branch as the input to the ARM deployment which simplifies the script a whole lot. Will investigate and confirm.
> Assuming that 2 is feasible it would be my preferred approach, but I'll differ to you and @LuiseFreese as your preference here and go that way
I let @LuiseFreese make the executive decision, but for me, it makes sense to go with Option 1. Option 2 is great but would always use the latest version from GitHub, and sometimes you'd like to checkout a moment in time and rerun it after days or weeks. I like it better when I checkout that point in time version and keep it on my CloudShell storage account.

> And I'm more than happy to help get this wrapped up.
Thank you, this is highly appreciated!

**Comment by gavinbarron** [comment]
There's another usecase that I think bears considering.
With using the -deploy Resource Group and storage account users who have PowerShell + Azure CLI installed locally can choose to run the script locally and it will "just work". 
If we move to the assumption that this is only ever run from CloudShell as Option 1 locks in we stop these users from running the script locally.

**Comment by LuiseFreese** [comment]
First of  all thank you @gavinbarron for putting so much hard work into this ❤ Your expertise is HIGHLY appreciated - this will ease so much for everyone who deploys ProvisionGenie 🧞! 

Also thank you @YannickRe for reviewing, testing and bringing your expertise to the table! 
You both take this - yet again - to another level 🚀

my feedback: 

- container-issue: any prerequisites need to be documented and we should also give a hint in the script. assigning the correct permissions would be amazing. 
- Optional ResourceGroup parameter: yes please, we just need to change this then in the ARM template as well 
- Downloading template files: after a quick check with Yannick I think option 1 is the best for us at the moment. Do you @CarmenYsewijn have anything against that? 

Thanks again everyone, I am very much grateful for all your help 🙏

**Comment by gavinbarron** [comment]
I did some digging. There's a dedicated PowerShell cmdlet to get all the info about the storage account from cloud shell `Get-CloudDrive` This gives us everything we need to provision the SAS token and use the templates in the cloned repo.

Added PR #64 to fix the issues raised in here

**Comment by YannickRe** [comment]
Hi @gavinbarron , thank you for the awesome work and the quick turnaround! We're in the final stretch, just tested and noticed some small things (and one unfortunate thing)...

**ManagedIdentity rerun issue**
You adjusted the code to check for existing permission assignments, but it currently does not work. This is due to the following:
```
$currentRoles = (az rest `
>>     --method get `
>>     --uri https://graph.microsoft.com/v1.0/servicePrincipals/$principalId/appRoleAssignments `
>>     | ConvertFrom-Json).value `
>>     | ForEach-Object { $_.appRoleId }
```
returns
```
19dbc75e-c2e2-444c-a770-ec69d8559fc7
9492366f-7969-46a4-8d15-ed1a20078fff
23fc2474-f741-46ce-8465-674744c5c361
bf7b1a76-6e77-406b-b258-bf5c7720e98f
62a82d76-70ea-41e2-9197-370581804d09
0c0bf378-bf22-4481-8f81-9e89a9b4960a
```
but the following `$teamCreate = az ad sp show --id $graphId --query "appRoles[?value=='Team.Create'].id | [0]"` returns `"23fc2474-f741-46ce-8465-674744c5c361"` and as a result, the matching fails: $roleMatch = $currentRoles -match $appRoleId

**Non-existing subscription id**
If you provide a subscription id that does not exist, it tells you that it does not exist and then continues with the default subscription, instead of canceling. We prefer this "issue" to stop the execution.

**ProvisionGenieApp as optional parameter**
We'd like to provide the option to deploy ProvisionGenie multiple times in the same Azure, and as such we noticed that `ProvisionGenieApp` better not be hardcoded as an app name.
Could you maybe add this as an optional parameter?

**CloudShell as a storage account**
I had a chat with Luise, and we agree with your assessment that switching to CloudShell would disable the option to run the deployment locally. Additionally, the script fails when using a different subscription id because it cannot find CloudShell storage account IN that subscription etcetc.

So after a quick chat with @LuiseFreese , it looks like the best course of action is to revert the usage of CLoudShell and go back to the dedicated separate storage account.
We do like to change one thing tho, and feel like this storage account should be created in the main "ProvisionGenie" resource group instead of its own `-deploy` group.

I'm very sorry to not have assessed this better/sooner 😔

**Comment by LuiseFreese** [comment]
great work, guys! @YannickRe and @gavinbarron! 

here is one puzzle tile 🧩 to solve the ManagedIdentity rerun issue: we can replace 
`$teamCreate = az ad sp show --id $graphId --query "appRoles[?value=='Team.Create'].id | [0]"` 
by 
`$teamCreate = az ad sp show --id $graphId --query "appRoles[?value=='Team.Create'].id | [0]" -o tsv`

so that it outputs Tab-separated values, with no keys. 
for reference see [Output formats for Azure CLI commands](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli)

@YannickRe tested this successfully already 🥂

**Comment by gavinbarron** [comment]
**AAD App Name**
Greate idea, easy enough.

**Storage**
Sure, I can revert that and target the Storage Account to be inside the resource group being deployed. 
And don't worry about the churn on that, I got to learn stuff with the change.
I'll change the permission assignment to grant the user running the script Contributor on the Resource Group being deployed which will prevent the issue we saw with classic admins.

**Managed Identity Permissions**
Weird, I tested the Managed Identity permissions piece a few times, admittedly it was a little late. Shouldn't be too hard to make it work right.

**Managed Identity Location**
Not sure if you spotted that I'd changed the location of the Managed Identity to be passed down from the parent template rather than hard coded to `westeurope`. This could be considered a breaking change 😦 as anyone who has deployed with the Managed Identity in westeurope and their ResourceGroup elsewhere attempting to re-deploy will have the deployment fail as you can't change the location of a resource.
This can be reverted if you think it necessary, but it seemed like an error when I spotted it last night.

**Comment by YannickRe** [comment]
> Storage

Good idea.

> Managed Identity Permissions

No worries. Just adding the `--output tsv` to fetching the permission scope id's (all of them) will fix this.

> Managed Identity Location

I saw, and it is accepted 😀. For future deployments, it is better that this is not hardcoded.

**Comment by gavinbarron** [comment]
PR #65 should address the items raised thus far :)

**Comment by YannickRe** [comment]
@gavinbarron impressive work! I tested and retested it, tried many different parameter combinations and it now seems super robust and stable. Thank you for this effort, the team and I appreciate it enormously!

There are two more things before we can merge:
- @LuiseFreese / @carmenysewijn will need to do an addition documentation check, to make sure the docs are still end-to-end consistent with the new approach and all the changes we made. It looks like it from my side, but I prefer a second opinion
- The script changes the order of some installation instructions, and we suspect this has an impact but we haven't been able to fully pinpoint it. Before we merge, we need to make sure what it is and what our approach is to handle this. We'll circle back asap!

I'm so excited to get this done: the timesaving is gigantic🚀

**Comment by gavinbarron** [comment]
Oh, @LuiseFreese do we need the AAD App registered before deploying the Dataverse pieces?

In that case there are two options:
- Add a pause using a Read-Line input check into the script that so that we can create the app registration and then stop until the user gives input to continue execution
- Split the script in two and output the ClientId. ClientSecret, TenantId from the first for input into the second

**Comment by YannickRe** [comment]
@gavinbarron This went a bit faster than expected 😊.
First the issue: We need the app registration first to make the Application user in Dataverse, otherwise the Logic Apps can't register their webhooks with the Dataverse tables.

@LuiseFreese already restructured the docs to accommodate for this, to make it more clear for you what needs to happen. It seems you noticed from the commits 😁😉.

Indeed, those are the two options that we discussed and the decision fell on the second one. Not sure we need the tenant id as input? We could assume it from the logged-in user, if necessary?
Our idea:
- Run the App Registration script, output client id / secret (/ tenant id?)
- Go to Dataverse, do the required steps
- Run the second script with the rest of the deployment, taking client id and secret as input

We have been asking a lot from you already, so if this is too much: we can do this part too. Please don't feel obliged, we're already super grateful for your contributions.

**Comment by LuiseFreese** [comment]
+1 
super happy, grateful and very much impressed on this. This totally rocks!

**Comment by gavinbarron** [comment]
I'll make the changes to split the script later tonight :)

**Comment by gavinbarron** [comment]
I realized that we can differ resetting the client app credentials until during the main deployment. 

This should allow leaving the current parameter list to the main deployment script unchanged :)

Hopefully this approach works.

**Comment by YannickRe** [comment]
@gavinbarron What a great realisation! I glanced over the commit, and it sure looks like this should do the trick.
I will test further this evening and then we can et this thing merged for all to use 😀. Great work, again!

**Comment by YannickRe** [comment]
@gavinbarron Made some final tweaks:
- We don't need subscription information to do the app registration, it doesn't depend on a subscription so I removed that from the first script
- The app registration result has a `password` property instead of a `clientCredential` property, and a `tenant` property instead of a `tenantId` property. I adjusted the script for that.
- Passing the app registration properties into the ARM deploy command required extra encapsulation with `$()`, so I adjusted the script for this.

It all works now, the whole thing is deployed in minutes and a new entry in Dataverse kicks off the provisioning!
Amazing work! I'm very excited for this, it's so much easier now!
Thank you for the effort, it was great working with you on this ♥.

THis leaves the executive decision with @LuiseFreese and @CarmenYsewijn to merge it 😁.

**Comment by gavinbarron** [comment]
WRT subscriptionId and tenantId. 
The challenge I was allowing for becomes apparent when you have CLI access to multiple Subscriptions with different AAD tenants.
If you're looking to target a subscription and tenant other than the one associated with the current default subscription then you cannot without either having the SubscriptionId parameter to switch the active subscription, or manually doing so beforehand.

**Comment by YannickRe** [comment]
Oh oh, that's a scenario I didn't think about. The different subscriptions doesn't really matter, but multiple tenants might become an issue 😀. Let me reset that quickly...

**Comment by LuiseFreese** [comment]
What an amazing work! Thank you so much! I love how you elegantly splitted the script and how you envisioned scenarios that at least didn't had in mind in the first place (but that made so much sense!). Thank you for bearing with all of our improvement-requests and for contributing to this open-source project. This only exists because of community and I am happy that you are part of it. I couldn't be happier to have your support and I am incredibly grateful that you put so much effort into this.

A big thank you also on behalf of the entire team 💖

**Comment by YannickRe** [comment]
☝☝ what she said, so it is now merged 😁

**Pull request merged**
